<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="Windows 7" host="PC206201"><DocLocation><![CDATA[C:\Users\312356\Desktop\CRAFT - Flight Application\Test Scripts\Scenario1\TC2]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[TC2]]></DName>
<Res><![CDATA[Scenario1_TC2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:25]]></Time>
<TimeTick>1401532645</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:26]]></Time>
<TimeTick>1401532646</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:26]]></Time>
<TimeTick>1401532646</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:26]]></Time>
<TimeTick>1401532646</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Invoke Application]]></Obj>
<Details ><![CDATA[Invoking application present at C:\\Program Files\\HP\\Unified Functional Testing\\samples\\flight\\app\\flight4a.exe]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:28]]></Time>
<TimeTick>1401532648</TimeTick>
<NodeArgs eType="User" icon="6" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Invoke Application]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:29]]></Time>
<TimeTick>1401532649</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:29]]></Time>
<TimeTick>1401532649</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:30]]></Time>
<TimeTick>1401532650</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:30]]></Time>
<TimeTick>1401532650</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:30]]></Time>
<TimeTick>1401532650</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run "C:\\Program Files\\HP\\Unified Functional Testing\\samples\\flight\\app\\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\\Program Files\\HP\\Unified Functional Testing\\samples\\flight\\app\\flight4a.exe",1]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:30]]></Time>
<TimeTick>1401532650</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\\Program Files\\HP\\Unified Functional Testing\\samples\\flight\\app\\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="21" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[Verify Invoke]]></Obj>
<Details ><![CDATA[Application invoked successfully]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:30]]></Time>
<TimeTick>1401532650</TimeTick>
<NodeArgs eType="User" icon="6" nRep="23" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Verify Invoke]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:31]]></Time>
<TimeTick>1401532651</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:31]]></Time>
<TimeTick>1401532651</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["acoe"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:31]]></Time>
<TimeTick>1401532651</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["487c2bfbe0d183b71d9174b4cfefafc1b9ad1ca9"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:31]]></Time>
<TimeTick>1401532651</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:31]]></Time>
<TimeTick>1401532651</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Login]]></Obj>
<Details ><![CDATA[Login credentials entered for user: acoe]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:32]]></Time>
<TimeTick>1401532652</TimeTick>
<NodeArgs eType="User" icon="6" nRep="33" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[NewOrder.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="38" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[NewOrder.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj ><![CDATA[Initialize Order]]></Obj>
<Details ><![CDATA[Initializing a new order]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<NodeArgs eType="User" icon="6" nRep="39" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Initialize Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Date of Flight:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["12/27/20"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Date of Flight:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Date of Flight:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="44" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Date of Flight:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Fly From:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:35]]></Time>
<TimeTick>1401532655</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly From:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Fly To:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="48" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly To:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Flights Table]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[From.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="53" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[From.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="55" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flights Table]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="57" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Cognizant"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="59" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Economy.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="61" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Economy.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Tickets:.SetSelection]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:36]]></Time>
<TimeTick>1401532656</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="63" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Tickets:.SetSelection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Tickets:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:37]]></Time>
<TimeTick>1401532657</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="65" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Tickets:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Insert Order.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:37]]></Time>
<TimeTick>1401532657</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:42]]></Time>
<TimeTick>1401532662</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="69" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="41" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[Insert Order]]></Obj>
<Details ><![CDATA[Inserting a new order]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:42]]></Time>
<TimeTick>1401532662</TimeTick>
<NodeArgs eType="User" icon="6" nRep="70" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:43]]></Time>
<TimeTick>1401532663</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Order Status.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", "Insert Done...", "Insert Done...", 10000]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:43]]></Time>
<TimeTick>1401532663</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Order Status.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="72" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Verify Insert]]></Obj>
<Details ><![CDATA[Order inserted successfully]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:43]]></Time>
<TimeTick>1401532663</TimeTick>
<NodeArgs eType="User" icon="6" nRep="74" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Verify Insert]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Output value]]></Obj>
<Details ><![CDATA[Output value 23 written into the Order_No column]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:43]]></Time>
<TimeTick>1401532663</TimeTick>
<NodeArgs eType="User" icon="6" nRep="75" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Output value]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:44]]></Time>
<TimeTick>1401532664</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:44]]></Time>
<TimeTick>1401532664</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="78" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[NewOrder.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:45]]></Time>
<TimeTick>1401532665</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="80" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[NewOrder.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="77" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Initialize Order]]></Obj>
<Details ><![CDATA[Initializing a new order]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:45]]></Time>
<TimeTick>1401532665</TimeTick>
<NodeArgs eType="User" icon="6" nRep="81" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Initialize Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:45]]></Time>
<TimeTick>1401532665</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Date of Flight:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["12/27/20"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:45]]></Time>
<TimeTick>1401532665</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="84" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Date of Flight:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Date of Flight:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicTab&gt"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:45]]></Time>
<TimeTick>1401532665</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="86" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Date of Flight:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Fly From:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Denver"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:45]]></Time>
<TimeTick>1401532665</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="88" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly From:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Fly To:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="90" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly To:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="92" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Flights Table]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[From.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="95" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[From.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="97" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="94" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flights Table]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="99" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["R&D"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="101" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Economy.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="103" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Economy.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Tickets:.SetSelection]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 1]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:46]]></Time>
<TimeTick>1401532666</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="105" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Tickets:.SetSelection]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Tickets:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:47]]></Time>
<TimeTick>1401532667</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="107" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Tickets:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Insert Order.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:47]]></Time>
<TimeTick>1401532667</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="109" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Flight Reservation.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:52]]></Time>
<TimeTick>1401532672</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="111" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation.Activate]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="83" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[Insert Order]]></Obj>
<Details ><![CDATA[Inserting a new order]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:52]]></Time>
<TimeTick>1401532672</TimeTick>
<NodeArgs eType="User" icon="6" nRep="112" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Insert Order]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:52]]></Time>
<TimeTick>1401532672</TimeTick>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Order Status.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", "Insert Done...", "Insert Done...", 10000]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:52]]></Time>
<TimeTick>1401532672</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="115" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Order Status.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="114" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj ><![CDATA[Verify Insert]]></Obj>
<Details ><![CDATA[Order inserted successfully]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:52]]></Time>
<TimeTick>1401532672</TimeTick>
<NodeArgs eType="User" icon="6" nRep="116" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Verify Insert]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj ><![CDATA[Output value]]></Obj>
<Details ><![CDATA[Output value 24 written into the Order_No column]]></Details>
<Time><![CDATA[5/31/2014 - 16:07:53]]></Time>
<TimeTick>1401532673</TimeTick>
<NodeArgs eType="User" icon="6" nRep="117" Source="Action1" SourceLine="-1" >